using System;using System.Configuration;using System.Data;using System.Data.SqlClient;
namespace Task05{public partial class Marksheet:System.Web.UI.Page{
string cs=ConfigurationManager.ConnectionStrings["CollegeDB"].ConnectionString;
protected void Page_Load(object s,EventArgs e){if(!IsPostBack)LoadGrid();}
void Values(SqlCommand q){int a=int.Parse(txtS1.Text),b=int.Parse(txtS2.Text),c=int.Parse(txtS3.Text);int t=a+b+c;double p=t/3.0;string r=(a>=35&&b>=35&&c>=35)?"PASS":"FAIL";q.Parameters.AddWithValue("@id",txtId.Text);q.Parameters.AddWithValue("@n",txtName.Text);q.Parameters.AddWithValue("@c",txtCourse.Text);q.Parameters.AddWithValue("@s1",a);q.Parameters.AddWithValue("@s2",b);q.Parameters.AddWithValue("@s3",c);q.Parameters.AddWithValue("@t",t);q.Parameters.AddWithValue("@p",p);q.Parameters.AddWithValue("@r",r);}
void Exec(string sql,string msg){try{using(SqlConnection c=new SqlConnection(cs))using(SqlCommand q=new SqlCommand(sql,c)){Values(q);c.Open();q.ExecuteNonQuery();lblMessage.Text=msg;LoadGrid();}}catch(Exception x){lblMessage.Text="Error: "+x.Message;}}
protected void btnAdd_Click(object s,EventArgs e){Exec("INSERT INTO MarkSheets VALUES(@id,@n,@c,@s1,@s2,@s3,@t,@p,@r)","Added.");}
protected void btnUpdate_Click(object s,EventArgs e){Exec("UPDATE MarkSheets SET StudentName=@n,Course=@c,Subject1=@s1,Subject2=@s2,Subject3=@s3,Total=@t,Percentage=@p,Result=@r WHERE StudentId=@id","Updated.");}
protected void btnDelete_Click(object s,EventArgs e){try{using(SqlConnection c=new SqlConnection(cs))using(SqlCommand q=new SqlCommand("DELETE FROM MarkSheets WHERE StudentId=@id",c)){q.Parameters.AddWithValue("@id",txtId.Text);c.Open();q.ExecuteNonQuery();lblMessage.Text="Deleted.";LoadGrid();}}catch(Exception x){lblMessage.Text="Error: "+x.Message;}}
protected void btnSearch_Click(object s,EventArgs e){try{using(SqlConnection c=new SqlConnection(cs))using(SqlCommand q=new SqlCommand("SELECT * FROM MarkSheets WHERE StudentId=@id",c)){q.Parameters.AddWithValue("@id",txtId.Text);c.Open();using(SqlDataReader r=q.ExecuteReader()){if(r.Read()){txtName.Text=r["StudentName"].ToString();txtCourse.Text=r["Course"].ToString();txtS1.Text=r["Subject1"].ToString();txtS2.Text=r["Subject2"].ToString();txtS3.Text=r["Subject3"].ToString();lblMessage.Text="Record found.";}else lblMessage.Text="Not found.";}}}catch(Exception x){lblMessage.Text="Error: "+x.Message;}}
void LoadGrid(){using(SqlConnection c=new SqlConnection(cs))using(SqlDataAdapter a=new SqlDataAdapter("SELECT * FROM MarkSheets",c)){DataTable t=new DataTable();a.Fill(t);gvMarks.DataSource=t;gvMarks.DataBind();}}
}}