CREATE DATABASE CollegeDB;
GO
USE CollegeDB;
CREATE TABLE Users(UserId INT IDENTITY PRIMARY KEY,Name NVARCHAR(100),Email NVARCHAR(150) UNIQUE,Password NVARCHAR(100));
CREATE TABLE Students(StudentId INT IDENTITY PRIMARY KEY,Name NVARCHAR(100),Email NVARCHAR(150) UNIQUE,Mobile NVARCHAR(20),Course NVARCHAR(100),Gender NVARCHAR(20),Address NVARCHAR(250),UserId NVARCHAR(150),Password NVARCHAR(100));
CREATE TABLE PasswordUsers(UserId NVARCHAR(150) PRIMARY KEY,Password NVARCHAR(100));
CREATE TABLE Employees(EmployeeId INT IDENTITY PRIMARY KEY,Name NVARCHAR(100),Email NVARCHAR(150),Phone NVARCHAR(20),Position NVARCHAR(100),Salary DECIMAL(18,2));
CREATE TABLE MarkSheets(StudentId INT PRIMARY KEY,StudentName NVARCHAR(100),Course NVARCHAR(100),Subject1 INT,Subject2 INT,Subject3 INT,Total INT,Percentage DECIMAL(5,2),Result NVARCHAR(20));